# version: "3.7"
version: '3'

services:
  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: sleep infinity
    volumes:
      - /data/projects/frappe/volumes/irradiaerp_apps-vol:/workspace/frappe-bench/apps:rw
      - /data/projects/frappe/volumes/irradiaerp_sites-vol:/workspace/frappe-bench/sites:rw
      - /data/projects/frappe/volumes/irradiaerp_assets-vol:/workspace/frappe-bench/sites/assets:rw
    ports:
      - "8000:8000"
      - "9000:9000"

  