version: '3'

services:
  # erpnext-nginx:
  #   image: frappe/erpnext-nginx:${VERSION}
  #   restart: on-failure
  #   environment:
  #     - VIRTUAL_PORT=80
  #     - FRAPPE_PY=erpnext-python
  #     - FRAPPE_PY_PORT=8000
  #     - FRAPPE_SOCKETIO=frappe-socketio
  #     - SOCKETIO_PORT=9000
  #     - LETSENCRYPT_HOST=${SITES}
  #     - VIRTUAL_HOST=${SITES}
  #     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  #   depends_on:
  #     - erpnext-python
  #     - frappe-socketio
  #     - frappe-worker-default
  #     - frappe-worker-long
  #     - frappe-worker-short
  #   links:
  #     - erpnext-python
  #     - frappe-socketio
  #     - frappe-worker-default
  #     - frappe-worker-long
  #     - frappe-worker-short
  #   volumes:
  #     - /data/projects/frappe/volumes/irradiaerp_sites-vol:/var/www/html/sites:rw
  #     - /data/projects/frappe/volumes/irradiaerp_assets-vol:/assets:rw
  #   ports:
  #     - "0.0.0.0:32873:80"

  erpnext-python:
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
    volumes:
      - /data/projects/frappe/volumes/irradiaerp_apps-vol:/home/frappe/frappe-bench/apps:rw
      - /data/projects/frappe/volumes/irradiaerp_sites-vol:/home/frappe/frappe-bench/sites:rw
      - /data/projects/frappe/volumes/irradiaerp_assets-vol:/home/frappe/frappe-bench/sites/assets:rw
    ports:
      - "0.0.0.0:32871:8000"

  frappe-socketio:
    image: frappe/frappe-socketio:${VERSION}
    restart: on-failure
    depends_on:
      - redis-socketio
    links:
      - redis-socketio
    volumes:
      - /data/projects/frappe/volumes/irradiaerp_sites-vol:/home/frappe/frappe-bench/sites:rw
    ports:
      - "0.0.0.0:32872:9000"

  frappe-worker-default:
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - /data/projects/frappe/volumes/irradiaerp_apps-vol:/home/frappe/frappe-bench/apps:rw
      - /data/projects/frappe/volumes/irradiaerp_sites-vol:/home/frappe/frappe-bench/sites:rw

  frappe-worker-short:
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - /data/projects/frappe/volumes/irradiaerp_apps-vol:/home/frappe/frappe-bench/apps:rw
      - /data/projects/frappe/volumes/irradiaerp_sites-vol:/home/frappe/frappe-bench/sites:rw

  frappe-worker-long:
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - /data/projects/frappe/volumes/irradiaerp_apps-vol:/home/frappe/frappe-bench/apps:rw
      - /data/projects/frappe/volumes/irradiaerp_sites-vol:/home/frappe/frappe-bench/sites:rw

  frappe-schedule:
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - /data/projects/frappe/volumes/irradiaerp_apps-vol:/home/frappe/frappe-bench/apps:rw
      - /data/projects/frappe/volumes/irradiaerp_sites-vol:/home/frappe/frappe-bench/sites:rw

networks:
  default:
    external:
      name: webproxy